---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: demo-message
  labels:
    app: demo-message
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: demo-message
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
