---
apiVersion: v1
kind: Service
metadata:
  name: demo-message
  labels:
    app: demo-message
spec:
  selector:
    app: demo-message
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: http
