##############
# Release App
##############
name: 'Release Container App'

on:
  workflow_dispatch:
    inputs:
      container_image:
        type: string
        required: true
        default: tctestacr.azurecr.io/demo-message:main
      environment_name:
        type: string
        required: true
        default: dev
      namespace:
        type: string
        required: true
        default: dev

env:
  manifestsPath: ${{ github.workspace }}/manifests

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment_name }}
    steps:
    - uses: actions/checkout@v2
    - uses: Azure/k8s-set-context@v2
      with:
        kubeconfig: ${{ secrets.kubeconfig }}
    - uses: Azure/k8s-bake@v2.2
      id: bake
      with:
        renderEngine: kustomize
        kustomizationPath: ${{ env.manifestsPath }}
    - uses: Azure/k8s-deploy@v3.0
      with:
        namespace: ${{ github.event.inputs.namespace }}
        manifests: ${{ steps.bake.outputs.manifestsBundle }}
        images: |
          ${{ github.event.inputs.containerImage }}
        
